[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
whisper_market = "AL8vd4XrR2xWLjHCsMUQHYnEtYR8BoMYXgySJGGkJSQ4"

[programs.devnet]
whisper_market = "AL8vd4XrR2xWLjHCsMUQHYnEtYR8BoMYXgySJGGkJSQ4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
