[package]
name = "enroll_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bs58 = "0.5.1"
solana-sdk = "1.18.20"
solana-client = "1.18.20"
solana-program = "1.18.20"
borsh = "1.5.1"
solana-idlgen = { git = "https://github.com/deanmlittle/solana-idlgen.git" }
